# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cnstr.xdc

# Block Designs: bd/design_base/design_base.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_base || ORIG_REF_NAME==design_base} -quiet] -quiet

# IP: bd/design_base/ip/design_base_clk_wiz_0_0/design_base_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_base_clk_wiz_0_0 || ORIG_REF_NAME==design_base_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_base/ip/design_base_microblaze_riscv_0_0/design_base_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_base_microblaze_riscv_0_0 || ORIG_REF_NAME==design_base_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/design_base/ip/design_base_dlmb_v10_0/design_base_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_base_dlmb_v10_0 || ORIG_REF_NAME==design_base_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_base/ip/design_base_ilmb_v10_0/design_base_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_base_ilmb_v10_0 || ORIG_REF_NAME==design_base_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_base/ip/design_base_dlmb_bram_if_cntlr_0/design_base_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_base_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_base_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_base/ip/design_base_ilmb_bram_if_cntlr_0/design_base_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_base_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_base_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_base/ip/design_base_lmb_bram_0/design_base_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_base_lmb_bram_0 || ORIG_REF_NAME==design_base_lmb_bram_0} -quiet] -quiet

# IP: bd/design_base/ip/design_base_mdm_1_0/design_base_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_base_mdm_1_0 || ORIG_REF_NAME==design_base_mdm_1_0} -quiet] -quiet

# IP: bd/design_base/ip/design_base_rst_clk_wiz_0_100M_0/design_base_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_base_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==design_base_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/design_base/ip/design_base_axi_uartlite_0_0/design_base_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_base_axi_uartlite_0_0 || ORIG_REF_NAME==design_base_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_base/ip/design_base_axi_smc_0/design_base_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_base_axi_smc_0 || ORIG_REF_NAME==design_base_axi_smc_0} -quiet] -quiet

# Block Designs: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/bd_eb6c.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_1/bd_eb6c_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_2/bd_eb6c_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_3/bd_eb6c_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_4/bd_eb6c_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_5/bd_eb6c_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_6/bd_eb6c_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_7/bd_eb6c_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_8/bd_eb6c_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_9/bd_eb6c_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_10/bd_eb6c_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_11/bd_eb6c_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_12/bd_eb6c_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_13/bd_eb6c_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_14/bd_eb6c_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_15/bd_eb6c_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_16/bd_eb6c_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_17/bd_eb6c_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_18/bd_eb6c_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_19/bd_eb6c_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_20/bd_eb6c_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_21/bd_eb6c_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_22/bd_eb6c_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_23/bd_eb6c_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_24/bd_eb6c_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_25/bd_eb6c_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_26/bd_eb6c_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_27/bd_eb6c_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_28/bd_eb6c_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_29/bd_eb6c_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_30/bd_eb6c_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_31/bd_eb6c_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_32/bd_eb6c_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_33/bd_eb6c_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_34/bd_eb6c_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_35/bd_eb6c_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_36/bd_eb6c_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_37/bd_eb6c_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_38/bd_eb6c_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_39/bd_eb6c_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/design_base/ip/design_base_i2s_0_0/design_base_i2s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_base_i2s_0_0 || ORIG_REF_NAME==design_base_i2s_0_0} -quiet] -quiet

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_clk_wiz_0_0/design_base_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_base_clk_wiz_0_0 || ORIG_REF_NAME==design_base_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_clk_wiz_0_0/design_base_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_base_clk_wiz_0_0 || ORIG_REF_NAME==design_base_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_clk_wiz_0_0/design_base_clk_wiz_0_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_microblaze_riscv_0_0/design_base_microblaze_riscv_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_base_microblaze_riscv_0_0 || ORIG_REF_NAME==design_base_microblaze_riscv_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_microblaze_riscv_0_0/design_base_microblaze_riscv_0_0_ooc_debug.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_lmb_bram_0/design_base_lmb_bram_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_mdm_1_0/design_base_mdm_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_base_mdm_1_0 || ORIG_REF_NAME==design_base_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_mdm_1_0/design_base_mdm_1_0_ooc_trace.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_rst_clk_wiz_0_100M_0/design_base_rst_clk_wiz_0_100M_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_base_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==design_base_rst_clk_wiz_0_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_uartlite_0_0/design_base_axi_uartlite_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_base_axi_uartlite_0_0 || ORIG_REF_NAME==design_base_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_uartlite_0_0/design_base_axi_uartlite_0_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_1/bd_eb6c_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_2/bd_eb6c_arinsw_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_3/bd_eb6c_rinsw_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_4/bd_eb6c_awinsw_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_5/bd_eb6c_winsw_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_6/bd_eb6c_binsw_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_7/bd_eb6c_aroutsw_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_8/bd_eb6c_routsw_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_9/bd_eb6c_awoutsw_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_10/bd_eb6c_woutsw_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_11/bd_eb6c_boutsw_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_12/bd_eb6c_arni_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_13/bd_eb6c_rni_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_14/bd_eb6c_awni_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_15/bd_eb6c_wni_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_16/bd_eb6c_bni_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_20/bd_eb6c_s00a2s_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_21/bd_eb6c_sarn_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_22/bd_eb6c_srn_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_23/bd_eb6c_sawn_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_24/bd_eb6c_swn_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_25/bd_eb6c_sbn_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_26/bd_eb6c_m00s2a_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_27/bd_eb6c_m00arn_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_28/bd_eb6c_m00rn_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_29/bd_eb6c_m00awn_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_30/bd_eb6c_m00wn_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_31/bd_eb6c_m00bn_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_33/bd_eb6c_m01s2a_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_34/bd_eb6c_m01arn_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_35/bd_eb6c_m01rn_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_36/bd_eb6c_m01awn_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_37/bd_eb6c_m01wn_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/bd_0/ip/ip_38/bd_eb6c_m01bn_0_ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/ooc.xdc

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/ip/design_base_axi_smc_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_base_axi_smc_0 || ORIG_REF_NAME==design_base_axi_smc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/tesi2s/base/base.gen/sources_1/bd/design_base/design_base_ooc.xdc
