set_property SRC_FILE_INFO {cfile:D:/Vivado-projects/Basys3/sbml/microblazev_tutorial/microblazev_tutorial.srcs/constrs_1/new/microblaze_soc.xdc rfile:../../../microblazev_tutorial.srcs/constrs_1/new/microblaze_soc.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W5   IOSTANDARD LVCMOS33 } [get_ports sys_clock]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U18   IOSTANDARD LVCMOS33 } [get_ports reset]
