# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/microblaze_soc.xdc

# Block Designs: bd/design_mysoc/design_mysoc.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mysoc || ORIG_REF_NAME==design_mysoc} -quiet] -quiet

# IP: bd/design_mysoc/ip/design_mysoc_clk_wiz_0_0/design_mysoc_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mysoc_clk_wiz_0_0 || ORIG_REF_NAME==design_mysoc_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_mysoc/ip/design_mysoc_microblaze_riscv_0_0/design_mysoc_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mysoc_microblaze_riscv_0_0 || ORIG_REF_NAME==design_mysoc_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/design_mysoc/ip/design_mysoc_dlmb_v10_0/design_mysoc_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mysoc_dlmb_v10_0 || ORIG_REF_NAME==design_mysoc_dlmb_v10_0} -quiet] -quiet

# IP: bd/design_mysoc/ip/design_mysoc_ilmb_v10_0/design_mysoc_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mysoc_ilmb_v10_0 || ORIG_REF_NAME==design_mysoc_ilmb_v10_0} -quiet] -quiet

# IP: bd/design_mysoc/ip/design_mysoc_dlmb_bram_if_cntlr_0/design_mysoc_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mysoc_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_mysoc_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_mysoc/ip/design_mysoc_ilmb_bram_if_cntlr_0/design_mysoc_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mysoc_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==design_mysoc_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/design_mysoc/ip/design_mysoc_lmb_bram_0/design_mysoc_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mysoc_lmb_bram_0 || ORIG_REF_NAME==design_mysoc_lmb_bram_0} -quiet] -quiet

# IP: bd/design_mysoc/ip/design_mysoc_mdm_1_0/design_mysoc_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mysoc_mdm_1_0 || ORIG_REF_NAME==design_mysoc_mdm_1_0} -quiet] -quiet

# IP: bd/design_mysoc/ip/design_mysoc_rst_clk_wiz_0_100M_0/design_mysoc_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mysoc_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==design_mysoc_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/design_mysoc/ip/design_mysoc_axi_uartlite_0_0/design_mysoc_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mysoc_axi_uartlite_0_0 || ORIG_REF_NAME==design_mysoc_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_mysoc/ip/design_mysoc_axi_smc_0/design_mysoc_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mysoc_axi_smc_0 || ORIG_REF_NAME==design_mysoc_axi_smc_0} -quiet] -quiet

# IP: bd/design_mysoc/ip/design_mysoc_axi_gpio_0_0/design_mysoc_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mysoc_axi_gpio_0_0 || ORIG_REF_NAME==design_mysoc_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_mysoc/ip/design_mysoc_axi_gpio_1_0/design_mysoc_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_mysoc_axi_gpio_1_0 || ORIG_REF_NAME==design_mysoc_axi_gpio_1_0} -quiet] -quiet

# XDC: d:/Vivado-projects/Basys3/sbml/microblazev_tutorial/microblazev_tutorial.gen/sources_1/bd/design_mysoc/design_mysoc_ooc.xdc
